#!/usr/bin/python
import argparse
import deployment

# Arguments.
parser = argparse.ArgumentParser()
parser.add_argument("--reseller", help="The reseller who is deploying the app.", required=True)
parser.add_argument("--domain", help="The domain name of the site you're creating.", required=True)
parser.add_argument("--app", help="The name of the software you are deploying.", required=True)
parser.add_argument("--version", help="The version of the app you wish to deploy. If left blank the latest version will be deployed.")
parser.add_argument("--server", help="The server you're deploying to.")

args = parser.parse_args()

newguy = deployment.deployment(args.domain, args.reseller, args.app)
newguy.deploy_to_production()
