#!/usr/bin/python
import MySQLdb
import os
from subprocess import call
from ssh import ssh
import argparse

parser = argparse.ArgumentParser()
parser.add_argument("domain", help="The domain name of the site you're destroying.")
parser.add_argument("--server", help="The server you're deploying to.")
args = parser.parse_args()

# Constants.
fpm_configs = "/usr/local/var/php5-fpm/"

# Connect to the sites database.
site_db = MySQLdb.connect(user = "teamcity", passwd="vAPDUgqR9J39", db="sites")
site_c = site_db.cursor()

domain = args.domain
if args.server != None:
	server = args.server
else:
	site_c.execute("select web_server from clients where domain = %s;", domain)
	if site_c.rowcount == 0:
		print "Sorry I don't know where that site is."
		exit(1)
	else:
		server = site_c.fetchone()[0]

# Connect.
c = ssh(server)

# Fix the portmap.
c.do("sed -i '/{0}/d' '{1}portmap.txt'".format(domain, fpm_configs))
c.do("httxt2dbm -v -i {0}portmap.txt -o {0}portmap.dbm".format(fpm_configs))

# Kill the fpm.
c.do("kill $(cat {0}{1}/running.pid)".format(fpm_configs, domain))

# Delete the fpm folder.
c.do("rm -r {0}{1}".format(fpm_configs, domain))

# Delete the user.
c.do("userdel -r {0}".format(domain))
c.close()

# Delete the database entry.
site_c.execute("delete from clients where domain = %s;", domain)
