#!/bin/bash
# Get the database 

# Get the parmaters to insert into the database.
url="$1"
user=$(awk -F: '{uid[$3]=1}END{for(x=50000; x<=60000; x++) {if(uid[x] != ""){}else{print x; exit;}}}' /etc/passwd)
port="$uid"
server="dev3"

# Insert the paramters into the database.


#useradd -d /usr/local/htdocs/"$site_name" -g nobody -u "$uid" "$uid"

#mkdir "/usr/local/htdocs/$site_name"
#chmod 750 "/usr/local/htdocs/$site_name"
#chown "${uid}:wheel" "/usr/local/htdocs/$site_name"

#mkdir "/usr/local/var/php-fpm/$site_name"
#chmod 750 "/usr/local/var/php-fpm/$site_name"
#chown "${uid}:wheel" "/usr/local/var/php-fpm/$site_name"
#echo "$uid"
